### ISSUE TITLE
Težave s kodo

### ISSUE THREAD

**Issue by marinasirk** [marinasirk/Shortest-matching#2]
Pozdravljeni,

sva naredile program v CoCalc-u, vendar imava problem, ker je pri nama x matrika in ne vektor vrednosti 0 in 1, zato nama ne dela. Zanima naju še, če sva prav definirali problem 2. Na repozitoriju je naložena koda, do katere lahko dostopate tudi na povezavi https://cocalc.com/projects/2af3130d-ead8-41f2-8233-c9312182d6a7/files/Shortest%20matching.sagews?session=default.

Lep pozdrav

**Comment by jaanos** [comment]
Indekse za `X` podajta znotraj enega para oglatih oklepajev - torej namesto `X[i][j]` pišita `X[i, j]`. Pazita tudi pri izpisovanju rešitve: `X` je še vedno spremenljivka in ne vsebuje rešitve - ta se nahaja v `resitev1`. Namesto `X[i][j]` torej tam pišita `resitev1[i, j]`.

Problem 2 izgleda v redu zastavljen, bi se ga pa dalo poenostaviti: spremenljivke `Y[i, j]`, kjer sta `i` in `j` iste barve, so nepotrebne; prav tako lahko zaradi simetričnosti fiksirata vrstni red barv in se omejita npr. samo na `i in range(d/2)` in `j in range(d/2, d)` (tj, upoštevata le zgornjo desno četrtino matrike razdalj). Tako odpadeta pogoja 3 in 4 ter prva zanka pri pogoju 1, tretjo zanko pa bi bilo treba spremeniti tako, da gre po `j` in sešteva po `i` (pri prvem problemu za to poskrbi že simetrija). Lahko bi šli še korak naprej in enostavno imeli splošno matriko razdalj med `i`-to rdečo in `j`-to modro točko, pa niti ne bi bilo potrebno ločiti točk po indeksih.

Mimogrede, svetujem, da datoteko na repozitoriju preimenujeta tako, da bo imela končnico `.sage` - da se ve, za kakšno datoteko gre, pa da bo GitHub ustrezno pobarval kodo. Za neposredni dostop do kode na CoCalc pa bi morali nastaviti, da je ta javna (levo zgoraj je meni **(i)**, tam pa opcija *Share...* in gumb **Make item public**).

**Comment by marinasirk** [comment]
Sedaj sva vse to popravili, vendar nama še vedno ne dela. Javi nama tole:

Error in lines 63-66
Traceback (most recent call last):
  File "/cocalc/lib/python2.7/site-packages/smc_sagews/sage_server.py", line 1009, in execute
    exec compile(block+'\n', '', 'single') in namespace, locals
  File "", line 3, in <module>
KeyError: (0, 0)
*** WARNING: Code contains non-ascii characters ***

Tudi če pustiva vrstice 63-66 prazne, še vedno javlja, da je napaka pri istih vrsticah.

**Comment by jaanos** [comment]
Ali lahko še enkrat naložita kodo na GitHub? Vrstice, ki se pojavijo v napakah, ne ustrezajo nujno prikazanemu številčenju.

**Comment by marinasirk** [comment]
Lahko, je pa tudi koda na CoCalc sedaj javna (https://cocalc.com/projects/2af3130d-ead8-41f2-8233-c9312182d6a7/files/Shortest%20matching.sagews?session=default).

**Comment by jaanos** [comment]
Problem je v tem, da npr. `Y[0, 0]` ni nikjer uporabljena in posledično tudi v rešitvi nima vrednosti.

Svetoval bi, da definirata matriko `B`, ki predstavlja zgornjo desno četrtino matrike `A`. Potem lahko razdalje dobita iz `B` - ta matrika seveda več ni simetrična, tako da bo treba v ciljni funkciji upoštevati vse njene vnose. Indeksi v obeh dimenzijah gredo sedaj od `0` do `d/2-1`.

Za lažje delo z matrikami bi svetoval, da že v funkciji `matrika_povezav` vrneta matriko, pretvorjeno z `numpy.array` ali `Matrix` (prejšnji ima lepši izpis, tako da lahko ostaneta pri tem). V obeh primerih lahko potem enostavno prideta do podmatrike:
```sage
B = A[:d/2, d/2:] # vrstice do izključno d/2, stolpci od vključno d/2
q.set_objective(sum(sum(B[i][j]*Y[i, j] for j in range(d/2)) for i in range(d/2)))
```
Omejitvi bosta potem povedali, da so vse vsote po stolpcih in po vrsticah enake 1. Vse zanke bodo seveda šle po `range(d/2)`.

**Comment by marinasirk** [comment]
Super, hvala, sedaj pa dela.
